#!/bin/bash

cd $(dirname $0)/..
aws logs delete-log-group --log-group-name /aws/lambda/zjtlambda
aws lambda delete-function --function-name zjtlambda

aws iam detach-role-policy --role-name zjt-lambda-test-role --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
aws iam detach-role-policy --role-name zjt-lambda-test-role --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
aws iam delete-role-policy --role-name zjt-lambda-test-role --policy-name cloudwatchPolicy
aws iam delete-role --role-name zjt-lambda-test-role

aws cloudformation delete-stack --stack-name cloudWatchTestStack
