version: "3"

services:

  nginx:
    container_name: thoughtworks-aws-training_docker_nginx
    image: nginx:1.14
    restart: always
    ports:
      - 80:80
    links:
      - server_apple:server_apple
      - server_boy:server_boy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/access.log:/var/log/nginx/access.log
    depends_on:
      - server_apple
      - server_boy

  server_apple:
    image: thoughtworks-aws-training_docker_server_apple:latest
    container_name: thoughtworks-aws-training_docker_server_apple
    hostname: server_apple
    build: webserver/ServerApple
    ports:
      - 8081:8080

  server_boy:
    image: thoughtworks-aws-training_docker_server_boy:latest
    container_name: thoughtworks-aws-training_docker_server_boy
    hostname: server_boy
    build: webserver/ServerBoy
    ports:
      - 8082:8080